model:
    arch: fcn16s
data:
    dataset: root
    train_split: train
    val_split: test
    img_rows: 'same'
    img_cols: 'same'
    path: /home2/bpch28/datasets/rootset
    mode: multi
training:
    train_iters: 215600
    batch_size: 1
    val_interval: 2156
    n_workers: 1
    print_interval: 100
    optimizer:
        name: 'sgd'
        lr: 1.0e-10
        weight_decay: 5.0e-3
        momentum: 0.99
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    resume: fcn16s_root.pkl
